# Generated by Django 2.2.6 on 2019-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtworesponses',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
