# Generated by Django 2.2.6 on 2019-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
