# Generated by Django 2.2.6 on 2019-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
