# Generated by Django 2.2.6 on 2019-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialform',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
    ]
