# Generated by Django 2.2.6 on 2019-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestmodel',
            old_name='name',
            new_name='your_name',
        ),
    ]
