# Generated by Django 2.2.6 on 2019-11-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initialform_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='initialform',
            name='cert_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
