# Generated by Django 2.2.6 on 2019-11-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_interestmodel_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtworesponses',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
