# Generated by Django 2.2.6 on 2019-11-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_formtworesponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtworesponses',
            old_name='participated_following',
            new_name='participated_job_project',
        ),
        migrations.RenameField(
            model_name='formtworesponses',
            old_name='spouse_employment',
            new_name='spouse_employment_detail',
        ),
    ]
