# Generated by Django 2.2.6 on 2019-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20191118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtworesponses',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
