# Generated by Django 2.2.6 on 2019-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initialform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialform',
            name='cert_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
