<<<<<<< HEAD
# Generated by Django 2.2.6 on 2019-11-18 15:10
=======
# Generated by Django 2.2.6 on 2019-11-19 06:11
>>>>>>> 0d1aba197aac588439d94f2b2ea26fbe2ab31469

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('access', '0002_auto_20191118_1735'),
=======
        ('access', '0002_interestmodel_is_sent'),
>>>>>>> 0d1aba197aac588439d94f2b2ea26fbe2ab31469
    ]

    operations = [
        migrations.AddField(
            model_name='formtworesponses',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
