# Generated by Django 2.2.6 on 2019-11-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_formtworesponses_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestmodel',
            old_name='name',
            new_name='your_name',
        ),
    ]
