# Generated by Django 2.2.6 on 2019-11-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20191113_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
        migrations.RenameField(
            model_name='initialform',
            old_name='cert_image',
            new_name='KCSE_certificate_image',
        ),
    ]
