# Generated by Django 2.2.6 on 2019-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20191113_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialform',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
