# Generated by Django 2.2.6 on 2019-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20191114_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtworesponses',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
